# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20170206_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='first_visit',
        ),
        migrations.RemoveField(
            model_name='page',
            name='last_visit',
        ),
    ]
