# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picure',
            new_name='picture',
        ),
    ]
